language: python

sudo: false

env:
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19
  - TOX_ENV=py34-django110
  - TOX_ENV=pypy-django17
  - TOX_ENV=pypy-django18
  - TOX_ENV=pypy-django19
  - TOX_ENV=pypy-django110
  - TOX_ENV=pypy5-django19
  - TOX_ENV=pypy5-django110


install:
  - pip install tox

script:
    - tox -e $TOX_ENV
